services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./config:/config
      - ${PWD}/dist:/config/www/custom_cards:rw
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment: []
