services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./config:/config
      - ${PWD}/dist:/config/www/custom_cards:rw
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment: []
  babybuddy:
    image: lscr.io/linuxserver/babybuddy
    container_name: babybuddy
    volumes:
      - ./babybuddy-config:/config
    ports:
      - 8100:8000
    restart: unless-stopped